version: '3.8'

services:
  php:
    build: ./php
    volumes:
      - ../backend:/var/www/html
    depends_on:
      - mysql
    env_file:
      - ../backend/.env

  # Add this scheduler service
  scheduler:
    build: ./php
    volumes:
      - ../backend:/var/www/html
    depends_on:
      - mysql
      - php
    env_file:
      - ../backend/.env
    command: >
      sh -c "
        while true; do
          php /var/www/html/artisan schedule:run --verbose --no-interaction
          sleep 60
        done
      "

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../backend/public:/var/www/html/public
    depends_on:
      - php

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: marketsleuth
      MYSQL_USER: sleuth
      MYSQL_PASSWORD: sleuth
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:6
    ports:
      - "6380:6379"

  node:
    image: node:20.19
    working_dir: /app
    volumes:
      - ../frontend:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "5173:5173"

volumes:
  mysql_data: